// Generated by CoffeeScript 1.12.7
(function() {
  $(function() {
    return app.initialize();
  });

  window.app = {
    chara: "",
    chara_number: "",
    my_hand: 0,
    your_hand: 0,
    my_life: 100,
    your_life: 100,
    my_victory: 0,
    your_victory: 0,
    round_count: 0,
    wait_time: 5000,
    your_hand_string: "",
    all_result: "",
    final_result: "",
    initialize: function() {
      this.setChara();
      this.beginTitle();
      this.mySetBind();
      this.checkLife();
      this.setPosition();
      this.checkMark();
      this.resetGame();
      this.returnTitle();
      return this.endGame();
    },
    beginTitle: function() {
      console.log("beginTitle");
      console.log(this.my_player);
      console.log(this.your_player);
      $('#start-button').click((function(_this) {
        return function() {
          console.log(_this.my_player);
          console.log(_this.your_player);
          $('#start-title').css('display', 'none');
          $('#game-screen').css('display', 'block');
          $('#my').html("<img src=\"./image/" + _this.my_player + "_stand.gif\">");
          $('#you').html("<img src=\"./image/" + _this.your_player + "_stand.gif\">");
          $('#gu').html("<img src=\"./image/select/" + _this.my_player + "_hado_gazou.jpg\">");
          $('#choki').html("<img src=\"./image/select/" + _this.my_player + "_shoryu_gazou.jpg\">");
          $('#pa').html("<img src=\"./image/select/" + _this.my_player + "_tatsumaki_gazou.jpg\">");
          $('#2pgu').html("<img src=\"./image/select/" + _this.your_player + "_hado_gazou.jpg\">");
          $('#2pchoki').html("<img src=\"./image/select/" + _this.your_player + "_shoryu_gazou.jpg\">");
          $('#2ppa').html("<img src=\"./image/select/" + _this.your_player + "_tatsumaki_gazou.jpg\">");
          return $('#block').animate({
            opacity: 0.0
          });
        };
      })(this));
      return $('service-button').click(function() {
        $('h1').css('display', 'none');
        $("#start-button").css('display', 'none');
        return $("#service-button").css('display', 'none');
      });
    },
    setChara: function() {
      var ALL_CHARACTERS, my_charanumber, your_charanumber;
      ALL_CHARACTERS = ["ryu", "ken", "goki"];
      my_charanumber = 2;
      this.my_player = ALL_CHARACTERS[my_charanumber];
      your_charanumber = 0;
      return this.your_player = ALL_CHARACTERS[your_charanumber];
    },
    mySetBind: function() {
      $('#gu').bind('click', (function(_this) {
        return function() {
          return _this.putAllHands(_this.my_player + "_gu", 0);
        };
      })(this));
      $('#choki').bind('click', (function(_this) {
        return function() {
          return _this.putAllHands(_this.my_player + "_choki", 1);
        };
      })(this));
      return $('#pa').bind('click', (function(_this) {
        return function() {
          return _this.putAllHands(_this.my_player + "_pa", 2);
        };
      })(this));
    },
    putAllHands: function(hand, my_hand) {
      this.my_hand = my_hand;
      console.log("hands");
      this.countupRound();
      this.choiceYouHand();
      this.changeMyHand(hand);
      this.showResult();
      this.checkLife();
      this.announceFinal();
      this.checkMark();
      this.nextGame();
      return this.endGame();
    },
    changeMyHand: function(hand) {
      if (this.round_count % 4 !== 0) {
        $('#my').html("<img src=\"./image/" + this.my_player + "skills/" + hand + ".gif\">");
        console.log("waza");
      }
      if (this.round_count % 4 === 0) {
        $('#my').html("<img src=\"./image/" + this.my_player + "skills/" + hand + "_ex.gif\">");
      }
      return console.log("exwaza");
    },
    choiceYouHand: function() {
      var your_hand_string;
      this.your_hand = _.random(0, 2);
      your_hand_string = [this.your_player + "_gu", this.your_player + "_choki", this.your_player + "_pa"];
      if (this.round_count % 4 !== 0) {
        $('#you').html("<img src=\"./image/" + this.your_player + "skills/" + your_hand_string[this.your_hand] + ".gif\">");
      }
      if (this.round_count % 4 === 0) {
        return $('#you').html("<img src=\"./image/" + this.your_player + "skills/" + your_hand_string[this.your_hand] + "_ex.gif\">");
      }
    },
    showResult: function() {
      var diff_hands;
      diff_hands = this.your_hand - this.my_hand;
      if ((diff_hands === -2) || (diff_hands === 1)) {
        this.all_result = "Hit!!";
      } else if (diff_hands === 0) {
        this.all_result = "アイコ";
      } else if ((diff_hands === -1) || (diff_hands === 2)) {
        this.all_result = "Damage!!";
      }
      return $('#result').html("<h>" + this.all_result + "</h>");
    },
    checkLife: function() {
      console.log("round_count in check life" + this.round_count);
      if (this.all_result === "Hit!!") {
        if (this.round_count % 4 !== 0) {
          this.your_life = this.your_life - 20;
        } else {
          this.your_life = this.your_life - 60;
          console.log("gon");
        }
        $('#your-life').attr({
          value: this.your_life
        });
      } else if (this.all_result === "Damage!!") {
        if (this.round_count % 4 !== 0) {
          this.my_life = this.my_life - 20;
        } else {
          this.my_life = this.my_life - 60;
        }
        $('#my-life').attr({
          value: this.my_life
        });
      }
      this.changemyHeart();
      return this.changeyourHeart();
    },
    changemyHeart: function() {
      var i, j, myHeart, ref, results;
      myHeart = "";
      results = [];
      for (i = j = 0, ref = this.my_life; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        results.push(myHeart = myHeart);
      }
      return results;
    },
    changeyourHeart: function() {
      var i, j, ref, results, yourHeart;
      yourHeart = "";
      results = [];
      for (i = j = 0, ref = this.your_life; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        results.push(yourHeart = yourHeart);
      }
      return results;
    },
    checkMark: function() {
      console.log("abc");
      console.log(this.final_result);
      if (this.final_result === "You Win!!") {
        this.my_victory = this.my_victory + 1;
        console.log("winner");
      } else if (this.final_result === "You Lose…") {
        this.your_victory = this.your_victory + 1;
      }
      this.addmyMark();
      return this.addyourMark();
    },
    addmyMark: function() {
      var i, j, ref;
      this.myMark = "";
      for (i = j = 0, ref = this.my_victory; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        this.myMark = this.myMark + "<img src=\"./image/winmark.jpg\">";
      }
      return $('#my-mark').html("<h>" + this.myMark + "</h>");
    },
    addyourMark: function() {
      var i, j, ref;
      this.yourMark = "";
      for (i = j = 0, ref = this.your_victory; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        this.yourMark = this.yourMark + "<img src=\"./image/winmark.jpg\">";
      }
      return $('#your-mark').html("<h>" + this.yourMark + "</h>");
    },
    setPosition: function() {
      return $('#my-choice').click((function(_this) {
        return function() {
          return setTimeout((function() {
            $('#my').html("<img src=\"./image/" + _this.my_player + "_stand.gif\">");
            $('#you').html("<img src=\"./image/" + _this.your_player + "_stand.gif\">");
            return $('#result').html("Get Ready...?");
          }), _this.wait_time);
        };
      })(this));
    },
    announceFinal: function() {
      console.log("yuorlife: " + this.your_life + ", mylife: " + this.my_life);
      if (this.your_life <= 0) {
        this.lockButton("You Win!!");
        $('#my').html("<img src=\"./image/" + this.my_player + "_victory.gif\">");
        $('#you').html("<img src=\"./image/" + this.your_player + "_lose.gif\">");
      } else if (this.my_life <= 0) {
        this.lockButton("You Lose…");
        $('#my').html("<img src=\"./image/" + this.my_player + "_lose.gif\">");
        $('#you').html("<img src=\"./image/" + this.your_player + "_victory.gif\">");
      }
      if (this.round_count === 12) {
        if (this.my_life > this.your_life) {
          this.lockButton("You Win!!");
          $('#my').html("<img src=\"./image/" + this.my_player + "_victory.gif\">");
          $('#you').html("<img src=\"./image/" + this.your_player + "_lose.gif\">");
        } else if (this.your_life > this.my_life) {
          this.lockButton("You Lose…");
          $('#my').html("<img src=\"./image/" + this.my_player + "_lose.gif\">");
          $('#you').html("<img src=\"./image/" + this.your_player + "_victory.gif\">");
        } else if (this.your_life === this.my_life) {
          this.lockButton("Draw Game");
          $('#my').html("<img src=\"./image/" + this.my_player + "_stand.gif\">");
          $('#you').html("<img src=\"./image/" + this.your_player + "_stand.gif\">");
        }
      }
      return $('#final-result').html("<h>" + this.final_result + "</h>");
    },
    countupRound: function() {
      this.round_count = this.round_count + 1;
      $('#count-round').html("<img src=\"./image/rounds/round_" + this.round_count + ".png\">");
      return console.log("count");
    },
    lockButton: function(final_result) {
      this.final_result = final_result;
      return $('#gu, #choki, #pa').unbind('click');
    },
    resetGame: function() {
      return $('#reset-button').bind('click', (function(_this) {
        return function() {
          $('#count-round').html("<img src=\"./image/rounds/round_1.png\">");
          _this.round_count = 0;
          $('#my').html("<img src=\"./image/" + _this.my_player + "_stand.gif\">");
          $('#you').html("<img src=\"./image/" + _this.your_player + "_stand.gif\">");
          $('#block').animate({
            opacity: 0.0
          });
          $('#my-life').attr({
            value: 100
          });
          $('#your-life').attr({
            value: 100
          });
          _this.my_victory = 0;
          _this.addmyMark();
          _this.your_victory = 0;
          _this.addyourMark();
          _this.my_life = 100;
          _this.your_life = 100;
          $('#result').html("Get Ready...?");
          $('#final-result').html("最終結果");
          if ((_this.final_result === "You Win!!") || (_this.final_result === "You Lose…") || (_this.final_result === "Draw Game")) {
            console.log("invalid");
            _this.mySetBind();
            return _this.final_result = "";
          }
        };
      })(this));
    },
    returnTitle: function() {
      return $('#title-button').bind('click', (function(_this) {
        return function() {
          $('#count-round').html("<img src=\"./image/rounds/round_1.png\">");
          _this.round_count = 0;
          $('#game-screen').css('display', 'none');
          $('#start-title').css('display', 'block');
          $('#my').html("<img src=\"./image/" + _this.my_player + "_stand.gif\">");
          $('#you').html("<img src=\"./image/" + _this.your_player + "_stand.gif\">");
          $('#block').animate({
            opacity: 0.0
          });
          $('#my-life').attr({
            value: 100
          });
          $('#your-life').attr({
            value: 100
          });
          _this.my_victory = 0;
          _this.addmyMark();
          _this.your_victory = 0;
          _this.addyourMark();
          _this.my_life = 100;
          _this.your_life = 100;
          $('#result').html("Get Ready...?");
          $('#final-result').html("最終結果");
          if ((_this.final_result === "You Win!!") || (_this.final_result === "You Lose…") || (_this.final_result === "Draw Game")) {
            console.log("invalid");
            _this.mySetBind();
            return _this.final_result = "";
          }
        };
      })(this));
    },
    nextGame: function() {
      console.log("nextgame");
      if ((this.final_result === "You Win!!") || (this.final_result === "You Lose…") || (this.final_result === "Draw Game")) {
        setTimeout(((function(_this) {
          return function() {
            $('#my').html("<img src=\"./image/" + _this.my_player + "_stand.gif\">");
            $('#you').html("<img src=\"./image/" + _this.your_player + "_stand.gif\">");
            $('#result').html("Get Ready...?");
            return $('#final-result').html("最終結果");
          };
        })(this)), this.wait_time);
        $('#count-round').html("<img src=\"./image/rounds/round_1.png\">");
        this.round_count = 0;
        $('#my-life').attr({
          value: 100
        });
        $('#your-life').attr({
          value: 100
        });
        this.mySetBind();
        this.final_result = "";
        this.my_life = 100;
        return this.your_life = 100;
      }
    },
    endGame: function() {
      console.log("endgame");
      if (this.my_victory === 2) {
        console.log("cuo");
        $('#block').html("<img src=\"./image/1pwins/" + this.my_player + "_win_" + this.your_player + "_lose.png\">");
        $('#block').animate({
          opacity: 1.0
        }, 2000);
        return this.lockButton("You Win!!");
      } else if (this.your_victory === 2) {
        $('#block').html("<img src=\"./image/2pwins/" + this.my_player + "_lose_" + this.your_player + "_win.png\">");
        $('#block').animate({
          opacity: 1.0
        }, 2000);
        return this.lockButton("You Lose…");
      }
    }
  };

}).call(this);
